### ISSUE TITLE
Add roadmap

### ISSUE THREAD

**Issue by owodunni** [velo-finance/fi.velotoken.ux#2]
There should be a link or a image of the current roadmap in the site. This will make it much simpler to find the current state of Velo. Currently one needs to dig through AMMs in Telegram inorder to find what the latest roadmap is.

The image modied by @cryptoburr https://t.me/Velotoken/23180 could be used.

![image](https://user-images.githubusercontent.com/8568146/103278358-944a0600-49cb-11eb-99bb-c616cf60f162.png)

Where should the roadmap be placed?
* As an image bellow to staking field?
* In a medium article that we link to?
* Something else?

**Comment by udwig** [comment]
We can place it next to the link you added in the pull-request #1, attach an on-click handler to make it a popup inside the page (no real popup, but more like an overlay), any other click would make the overlay disappear.

**Comment by owodunni** [comment]
Roger!
Do you think this is a good aproach for making it work?
https://github.com/benhowell/re-frame-modal
If not do you have a good link that I could have as starting point?

**Comment by udwig** [comment]
This re-frame-modal can give you some inspiration on how to approach it. It would be preferable to build it very specific into the code we already have. In `view.cljs`: 

![image](https://user-images.githubusercontent.com/71640096/103405986-567ae800-4b59-11eb-9043-bd15f7c5f98d.png)

You can add on the same level as the `div.app-content` a `div.app-modal`, style it so it overlays the whole screen and place the roadmap in it. To drive it add events to show or hide the modal. These events could change the `app-db` setting `:show-modal?` key to either `true` or `false`. 

Then create a `subscription` which reacts on the `:show-modal?` key in the app-db. Now you can use this subscription to show or hide the `div.app-modal`. You could use `(while @(<su [::subs/show-modal?]) [:div.app-modal ....the roadmap ...`

This would be a very specific implementation for the roadmap, we can easily generalize this in the future if we want to.

Have fun lisping 😄

**Comment by owodunni** [comment]
Thanks!
Great tutoring 🥇
